git:
  depth: 1
language: android
android:
  components:
    - tools
    - platform-tools
    # The tools section appears twice on purpose as itâ€™s 
    # required to get the newest Android SDK tools.
    - tools 
    - build-tools-27.0.1
    - android-26
matrix:
  fast_finish: true
notifications:
  email:
  - arnab@binary.com
  - amin@binary.com
  slack:
    secure: cdc/YPknARnKqvSta+BfYiV/YGRWvwpGHCKy6Bit6bFRSw0MBJowV4qI8m+8COcQHjmspAQ1P5uHiSG/v0bMDd8/KHRU2v3qSkraESXdGvm5HrsSomd8AYW8lK4sBV6iTVh/HIg+fI4yBxzIn3AhkOpyP9XrLKtwqYd8upISpfrUH0MrIrhb+XopZiEj8TS9FHvjwAZjRXZviieDHMztlPCxi8AsWxCZZ5e2eAu6+ry8GSmjO+gsEdXJ9mlhu7ZORMa6FFOYe1v4V512EChQUQjOh2oAIo2vid1QX46FriNS853DFJ8PjITqWaoeGuKXO92h7+wvDhAYp356Vtg4voIGNSK/xUiuT/1DIbJG2FG2Gb6UuSTxUgxPqgRa/QnjxJtdC/iH/SeK4nDa1FX6N1jU4GaZeUAccNPVGweBt6u46OfTGhgLaVf+qu7gv5Sc/8zR6d4xf9lJWqQqByJ5JmMf3rrviTDKLSne250bPR3G2KBZioTlppO4uZwfbfnCZjj/bK9hFsZ8z5KbM345+Ar9bO0QwcTF0a7hKUxAjy/tPHeD6q6ah3iHJJ03tgJcT8ylHpDkd10n/A7rAJdA0Nu8DHMqSJjXoEEF5KoKaWCu6AEJsEGqhocqz3j7eVaJKfQbCyYioXQYd0Sn6HOuwHQ1xjISb07gj0QtL++cRR8=
branches:
  only:
  - master
  - dev
  - qa
before_install:
  - set -e # terminate when any command returns non-zero code
  # cordova currently only works with node 6.x
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs
install: 
  - yarn install
  - yarn test:full
  - yarn test:coveralls
  - cd build
  - yarn install
  - cd ..
script:
  - cd build
  - yarn build
  - cd ..
after_success:
  - bash deploy-website.sh
before_deploy:
  # The code below will only run on qa branch
  - echo "The following files will be deployed to android app:"
  - ls ./www/
  - sudo npm install --global cordova
  - git tag "$(date +'%Y-%m-%dT%H%M')-$(git log --format=%h -1)" # Automatically tag a release
  - cordova platform add android
  - yarn build:android
  - mv ./platforms/android/build/outputs/apk/release/android-release-unsigned.apk ./platforms/android/build/outputs/apk/release/next-gen-beta-unsigned.apk 
deploy:
  provider: releases
  prerelease: true
  name: Next-Gen Prerelease $(date +'%Y-%m-%d %H:%M:%S')
  body: Release for QA testing! For official android app [Install from Google Play Store](https://play.google.com/store/apps/details?id=app.binary.com).
  api_key: $GIT_KEY
  file: "./platforms/android/build/outputs/apk/release/next-gen-beta-unsigned.apk"
  skip_cleanup: true
  on:
    repo: $TRAVIS_REPO_SLUG
    branch: qa
env:
  global:
    secure: TNtKNXrrpzNHvxffdoRKup1JjkRAkN79QhmHJ3s0MiU4QMyGM8Q/3MGhyWlbu1Uk/2BztsQhVy6qonS826QbjCquJkU4Rfs7cXvKnok8OOrQ8To3rSJazip4Bu4hPoW1QC60Jg/wZCzl7Htw6UP69akn5FLRT6REm6ScuzJRHrRfyyse5cztXO/3bokx5vULd+RhcmkUm+/o+4g6g0KtaPA84SC5EQZVGj0Z2Wckw/SsoGv++61sEFnmANFrvzJc6CsriRETSeU8eYxNqMQOPNJijXB22UUWdq+oDFzc52xi+cUpZNt/L+REv0r4XSunUY4OyaxZzciDril7hV4BuIrbuwoTZHaYv3FK2Oc36vbWVbT2Gkp+kUcuKI1QoTkMlXAMmfi39uwCizXVsU7e1fjDczIS+v8eu1gibKW93E2rMbcW/+n/T6d5VHPHPryNDjTW6cDOiZCugwhU5a9ovbcgsdK+3Uq76OXbQWKgaHm6Mj7DCoMwT7jf6BmCbwoaDUostueKrW9vxYNuaCYkiz8rrgBg24q4PO/XC+hExeIo7ZsD2J0PzEwMBqFgFGU19XQblioSLdy5jkMCYLjFX/BsLniHt4Lvm0bUdJw5ORRGRYfc3W2lwL/kf4jayNeP6rbIAKNEvU54ScBnMKHsiRRtVTgZUXDUasn8uM8dN+8=
